### PR TITLE
Event bus with unit testing

### PR DESCRIPTION
**Pull request by EricXDong**

### CODE REVIEW

**Comment by EricXDong** [comment]
@kochima @MakePLAN @mvescala please review and thumbs up if looks good

**Comment by MakePLAN** [comment]
When I am reviewing, do I need to test the code as well by pulling?

**Comment by EricXDong** [comment]
No you just have to look over the code and try to find anything missing/wrong if there is, otherwise thumbs up

**Comment by EricXDong** [comment]
issue #15

**Comment by MakePLAN** [comment]
It looks good to me.

**Pull request merged**
